### ISSUE TITLE
Set VersionName on PackageUploadRequest to a meaningful value.

### ISSUE THREAD

**Issue by jstvz** [SFDO-Tooling/CumulusCI#1142]
Currently `PackageUploadRequest` hardcodes the package name as the `VersionName` value. This results in package installation email containing a duplicated value, e.g.: 
> Your request to install package **"Affiliations Affiliations"** was successful.

With a meaningful name the same notification would read:
> Your request to install package **"Affiliations v10.8"** was successful.

Or, for simplicity of implementation the current date or ISO week could be used instead:
> Your request to install package **"Affiliations W27"** was successful.

**Comment by davisagli** [comment]
I did change this recently so that it's at least hardcoded as "Release" rather than duplicating the package name. https://github.com/SFDO-Tooling/CumulusCI/commit/f907e982d8959c79063cc0b590309973d8d349c0#diff-2c9adb50f93a369e1c8a1ac8b71a5b37R346

Including the version number would be ideal but is non-trivial because we would need to predict which number the platform will assign in advance.
