### ISSUE TITLE
Add Task to open and log into Workbench

### ISSUE THREAD

**Issue by spelak-salesforce** [SFDO-Tooling/CumulusCI#1152]
It would be very helpful to be able to open and log into [workbench.developerforce.com](https://workbench.developerforce.com) with a cci Task.

I'm not sure if it's even possible to log in via URL or API (if an API exists).

Currently
-  Opens [workbench.developerforce.com](https://workbench.developerforce.com) 
-  Calls `cci org info`
-  Copies <kbd>Username</kbd> into form on [workbench.developerforce.com](https://workbench.developerforce.com) 
-  Copies <kbd>Password</kbd> into form on [workbench.developerforce.com](https://workbench.developerforce.com)
-  Authorizes Workbench App for Scratch Org

**Comment by davisagli** [comment]
For scratch orgs (where we know the username/password) this might be possible to do using selenium -- but it would open up a new browser window rather than controlling your main one. Aside from that our ability to control a browser is limited to telling the OS to open a URL, so I don't think we would be able to populate the form.

For orgs connected using a connected app we wouldn't have the necessary credentials available.

**Comment by spelak-salesforce** [comment]
I found some info:
- Workbench [About](https://workbench.developerforce.com/about.php)
- Workbench Github: [forceworkbench/forceworkbench](https://github.com/forceworkbench/forceworkbench)

**Comment by davisagli** [comment]
Thanks for the pointers!

**Comment by davisagli** [comment]
Closing this since using the Salesforce CLI and VS Code extensions are encouraged in place of Workbench.
