### ISSUE TITLE
Trial Template - Error when Attempting to Login

### ISSUE THREAD

**Issue by mbeaty-sf** [SFDO-Tooling/CumulusCI#1283]
After spinning up a `Trial` Org template, after creation, waiting a while (as there is an error on first attempt to open if creating with `cci org browser trial` and you have to wait and refresh) and attempting to use `cci org browser` to login, I am met with 

"To access this page, you have to log in to Salesforce." or "Cannot log you in..."

This is intermittent for me, but here is the info of the org:

![image](https://user-images.githubusercontent.com/53280203/67604962-d32e5d00-f731-11e9-8a43-5e530c5d37c2.png)

This was run against version 3.0.2 of CCI

**Comment by davisagli** [comment]
@mbeaty-sf I was able to reproduce this. The weird thing is that after I got the login form from `cci org browser`, I tried going directly to the instance_url, and found that I was already logged in (probably from the first time I ran `cci org browser` and got the error). I then logged out, and then was able to successfully use `cci org browser` again. So I suspect this is something weird with Salesforce's session handling rather than with CumulusCI.

**Comment by davisagli** [comment]
@mbeaty-sf It is using the instance URL correctly; I was wrong on Friday about that being the source of the problem. It's redirecting to test.salesforce.com _after_ the access token is denied at the instance URL.

**Comment by mbeaty-sf** [comment]
Interesting! Ok, is there anything else I can look into or document to support this issue further?

**Comment by mbeaty-sf** [comment]
After leaving CCI for a bit, I came back and closed my browser, and then ran the `cci org browser trial` command to open my active trial org. I was presented with this that I have not seen before

![image](https://user-images.githubusercontent.com/53280203/67713961-27308000-f984-11e9-8ac3-951f26a45c1e.png)

**Comment by davisagli** [comment]
@mbeaty-sf have you see any more cases of this?

**Comment by mbeaty-sf** [comment]
I haven't seen this happen against since this time, but I also haven't tried to recreate...

**Comment by davisagli** [comment]
Closing this since I haven't heard reports of it in a while, but willing to reopen
