### ISSUE TITLE
scratch org is getting created on cci task run robot command

### ISSUE THREAD

**Issue by pronitagrawalvera** [SFDO-Tooling/CumulusCI#1439]
I am trying to run a robot test on CircleCI using the command cci task run robot, but it is creating the fresh org again as it executes.

I am using below commands,

venv/bin/cci flow run qa_org --org dev
venv/bin/cci task run robot --org dev -o suites robot/tests/Activities.robot -o include test -o vars LocalOrRemote:Local,Browser:googlechrome

First command i.e"venv/bin/cci flow run qa_org --org dev" this is creating new org and than pushing the code.
Second one "venv/bin/cci task run robot --org dev -o suites robot/tests.robot -o include test -o vars LocalOrRemote:Local,Browser:googlechrome" is creating new org than running the test cases

**Comment by prescod** [comment]
Hello @pronitagrawalvera :

Are you running the two commands back to back in the same directory?

Can you paste logs of what happens and use the github code snippet button to preserve line breaks?

https://help.github.com/en/github/writing-on-github/creating-and-highlighting-code-blocks

**Comment by pronitagrawalvera** [comment]
Yes, I am running the two commands back to back.

**Comment by prescod** [comment]
Can you paste logs please? Here or in a gist?

**Comment by pronitagrawalvera** [comment]
[build_1019_step_106_container_0.txt](https://github.com/SFDO-Tooling/CumulusCI/files/4029349/build_1019_step_106_container_0.txt)
![0702](https://user-images.githubusercontent.com/58841386/71876555-fc656380-314c-11ea-93d7-14744462d58b.PNG)
![0701](https://user-images.githubusercontent.com/58841386/71876573-04250800-314d-11ea-9630-7a7bbc42f5bd.PNG)

**Comment by pronitagrawalvera** [comment]
Any update on this?

**Comment by prescod** [comment]
Okay, I didn't realize that this was on CircleCI.

@boakley , @davisagli : Do we have any documentation about CCI & Robot on CircleCI?

I see an error in the log:

Keychain Error: Unable to store CumulusCI encryption key. You can configure it manually by setting the CUMULUSCI_KEY environment variable to a random 16-character string. 

ERROR: No recommended backend was available. Install a recommended 3rd party backend package; or, install the keyrings.alt package if you want to use the non-recommended backends. See https://pypi.org/project/keyring for details.

**Comment by davisagli** [comment]
@pronitagrawalvera looking at your CircleCI configuration that you shared in #1440, I think you'll need to make 2 changes:

1. Set the CUMULUSCI_KEY environment variable to a random 16-character string. CumulusCI uses this as an encryption key when writing files that store scratch org credentials. By default it creates a key and stores it in the system keychain. However, the error that @prescod noticed means that it is having trouble doing that, so it won't be able to store the org info. If you explicitly set CUMULUSCI_KEY, CumulusCI will use it instead of trying to generate and store a new one.

2. _Don't_ set the CUMULUSCI_KEYCHAIN_CLASS environment variable to cumulusci.core.keychain.EnvironmentProjectKeychain (This makes CumulusCI load org config information from environment variables rather than from the filesystem, so it won't find files that were saved by a previous execution of cci.)

**Comment by pronitagrawalvera** [comment]
Thanks, Issue is resoled with the above solution
