### ISSUE TITLE
Error for missing created and expired date

### ISSUE THREAD

**Issue by mgalalm** [SFDO-Tooling/CumulusCI#1471]
After upgrading to 3.3 we receive the below error, when we run _cci org import_ 

```
Traceback (most recent call last):
  File "/usr/local/bin/cci", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/cumulusci/cli/cci.py", line 209, in new_func
    func(config, *args, **kw)
  File "/usr/local/lib/python3.7/site-packages/cumulusci/cli/cci.py", line 856, in org_import
    scratch_org_config.config["date_created"] = parse_api_datetime(info["created_date"])
  File "/usr/local/lib/python3.7/site-packages/cumulusci/utils.py", line 37, in parse_api_datetime
    dt = datetime.strptime(value[0:DATETIME_LEN], API_DATE_FORMAT)
TypeError: 'NoneType' object is not subscriptable

```

We cobbled together a workaround by commenting out those newly introduced lines of code  
https://github.com/SFDO-Tooling/CumulusCI/blob/dec152e66363ae7cc16ca8fe9c59a4ddf28a4b46/cumulusci/cli/cci.py#L892-L893
By doing that everything went back to normal we would prefer a solution that goes to the core of the problem though, given that the project has no notion of scratch orgs, it uses only sandbox.

**Comment by davisagli** [comment]
@mgalalm The `cci org import` command is for importing a scratch org from the Salesforce CLI keychain. It can't work generally for sandboxes because if CumulusCI is configured to use a different connected app than the Salesforce CLI, then the imported org info won't include an oauth2 refresh token that CumulusCI can use. The recommended command for connecting a non-scratch org to CumulusCI is `cci org connect` (with the `--sandbox` flag when you're connecting a sandbox), which will prompt you to log in to the org through your browser.

**Comment by mgalalm** [comment]
Thanks a million @davisagli  , `cci org connect ` should work fine locally, it involves a manual step though _opening the browser and login_ . Meanwhile we use  `auth:sfdxurl:store` and passing sfdxurlfile to it, before running `cci org import` in our pipeline, I wonder is there any alternative way? I've done a fair bit of searching but with no luck :(

**Comment by davisagli** [comment]
@mgalalm for a non-interactive CI environment you can do this:
1. Connect the org locally and then run `cci org info [orgname] --json` to get its configuration as JSON, including the oauth2 refresh token.
2. In the CI environment, set the CUMULUSCI_KEYCHAIN_CLASS environment variable to `cumulusci.core.keychain.EnvironmentProjectKeychain`. This uses an alternate keychain that gets org and service config information from environment variables instead of files.
3. In the CI environment, set the CUMULUSCI_ORG_orgname environment variable (for example, if the org is named dev then set CUMULUSCI_ORG_dev) to the JSON from step 1.

**Comment by mgalalm** [comment]
Thank you very much @davisagli, will give it ago!

**Comment by jhgihub0** [comment]
“cci org info [orgname] --json” does not work for us. It fails with error:
Keychain Error: Unable to store CumulusCI encryption key. You can configure it manually by setting the CUMULUSCI_KEY environment variable to a random 16-character string. ERROR: No recommended backend was available. Install a recommended 3rd party backend package; or, install the keyrings.alt package if you want to use the non-recommended backends. See https://pypi.org/project/keyring for details.

In our automation in Jenkins we log in using SFDX, run cci, and then log out. There is not persistent connection, because we have multiple nodes and the job can run anywhere when executed.  

Before we set up the Jenkins job, we generated the force URL of our sandbox by running these commands:
sfdx force:auth:web:login --setalias OrgAlias --instanceurl https://test.salesforce.com
sfdx force:org:display -u OrgAlias –verbose
<img width="871" alt="image" src="https://user-images.githubusercontent.com/59979805/72562669-ef95ed80-3879-11ea-9dca-e8b0a9f64961.png">
sfdx force:auth:logout --targetusername OrgAlias --noprompt

We then stored the force:// URL in sfdx_login_force.txt

In our Jenkins job we do this to log in:
sfdx force:auth:sfdxurl:store --sfdxurlfile sfdx_login_force.txt --setalias orgAlias –setdefaultusername	

If we run “cci org import orgAlias orgAlias”, it work fine, but it assumes it’s a scratch org, and then fails at line 892 and 893 of CumulusCI/cumulusci/cli/cci.py

If we run “cci org connect -- sandbox orgAlias ”, then it tries to spawn a browser, but our Jenkins node is a Redhat Linux AWS machine with no UI.

Please advise how we can connect cci to an existing sandbox.
