### ISSUE TITLE
Add Retry Option to Robot Task

### ISSUE THREAD

**Issue by Julian88Tex** [SFDO-Tooling/CumulusCI#1713]
As a Quality Engineer, it would save time rerunning sometimes unstable steps to have them automatically retried a number of times that I define. It would also be helpful to have these results combined.

Notes:
- It appears this is possible with separate robot commands already: https://robotframework.org/robotframework/latest/RobotFrameworkUserGuide.html#merging-re-executed-tests

Possible Solution:
- Have an option similar to `retry_always` for `run_test` (https://cumulusci.readthedocs.io/en/latest/tasks.html?highlight=retry#run-tests) that is instead a number of retries. Based on the number of retries all failures will be attempted again a max number of times equal to number given in option. Also, all output logs will be combined into one file that is also viewable in metaCI.

**Comment by davisagli** [comment]
We're not going to do this as an option that applies to the entire robot task. We think that flaky test steps need to be taken one at a time with careful consideration of whether there's a way to make them solid -- and then only add a retry for that specific step if it's something that is flaky and out of our control. Otherwise we risk covering up problems that we want to discover and increasing the runtime of robot builds.
