### ISSUE TITLE
Allow for use of Force-App metadata in Unpackaged directory

### ISSUE THREAD

**Issue by Nickers3** [SFDO-Tooling/CumulusCI#1764]
**Please describe the nature of this feature request**
Many admins using SFDX and CCI are accustom to using the Force-App metadata structure.  Learning more about the use cases for the unmanaged and it's need to be setup using the src structure, this is confusing for admins using CCI.

**Describe the solution you'd like**
I'd love it if there was a way the unmanaged directory could be based on Force-App or src.  One idea would be it's own directory.  Or ability to set in yml file.

**Comment by Nickers3** [comment]
@mkolodner @davidmreed @coriobriensfdo this is something I'm discovering from working with the OmbudsmanCloudCare repo.  May or may not be using the right language here so happy to talk it through more.

**Comment by davidmreed** [comment]
@Nickers3 To clarify, it sounds like you are requesting the ability to utilize Salesforce DX format metadata in directories under `unpackaged`, such as `unpackaged/pre`, `unpackaged/post`, and `unpackaged/config/whatever`. Is that accurate?

**Comment by davisagli** [comment]
@Nickers3 We usually refer to the force-app structure as "sfdx format" because it's the format that sfdx assumes (it actually doesn't have to be force-app; the locations of package directories are specified in sfdx-project.json), and the more traditional format in src as "mdapi format" or Metadata API format.

CumulusCI supports both formats for the primary package directory in a project -- see https://cumulusci.readthedocs.io/en/latest/features.html#source-code-formats

For additional unpackaged metadata directories, there are a couple limitations in sfdx which make it difficult to support sfdx format:
1. CumulusCI uses the sfdx force:source:push command to deploy sfdx format metadata to an org, but this command does not have a way to specify a specific directory to deploy, so we don't have a way to deploy changes from the unpackaged directory without pushing changes from other directories, nor do we have a way that a directory gets deployed after another directory with metadata that it has references to.
2. Unpackaged metadata often needs to refer to packaged metadata. In order to work whether or not the package is installed as a managed package or not, and in namespaced scratch orgs or not, CumulusCI needs to do a step of replacing tokens with the actual namespace that is in effect. But sfdx force:source:push doesn't give us a way to hook in to do that at the necessary time during deployment.

Hopefully we'll figure out a way to work around these limitations at some point, but until then, the workaround is sticking with mdapi format for unpackaged metadata.

**Comment by Nickers3** [comment]
@davidmreed that's correct.  Sorry about the typo of unmanaged vs. unpackaged.

**Comment by Nickers3** [comment]
Good points @davisagli!

**Comment by davisagli** [comment]
@Nickers3 As of cumulusci 3.20.0, the `deploy` task can deploy folders of unpackaged metadata in sfdx format. (It detects this based on the absence of a package.xml file, and converts it to Metadata API format in a temporary directory.) This is uncharted territory so let me know if you try it and run into edge cases. One thing to keep in mind is that it probably won't make sense to use the sfdx push/pull commands with unpackaged metadata, since those commands include all directories listed in sfdx-project.json
