### ISSUE TITLE
EnvironmentProjectKeychain does not appear to work as intended

### ISSUE THREAD

**Issue by atrancandoris** [SFDO-Tooling/CumulusCI#2050]
**Describe the bug**
When setting the CUMULUSCI_KEYCHAIN_CLASS environment variable, as described in the [Cookbook](https://cumulusci.readthedocs.io/en/latest/cookbook.html?highlight=environmentprojectkeychain#create-a-github-action-workflow), to cumulusci.core.keychain.EnvironmentProjectKeychain, no environment variables are set upon creating orgs. After creating an org, running "cci org list" does not list the newly created org and no data about the org seems to persist.

For this reason, the cookbook for "Run headless browser tests" does not work and the scratch org is not deleted.

**Reproduction steps**
1. Set CUMULUSCI_KEYCHAIN_CLASS to cumulusci.core.keychain.EnvironmentProjectKeychain
2. Run a command which would create a scratch org such as "cci flow run dev_org --org dev"
3. Run "cci org list"
4. No orgs!

**Context**
CumulusCI version: 3.19.1 (/usr/local/Cellar/cumulusci/3.19.1/libexec/bin/cci) via brew
Python version: 3.8.5 (/usr/local/opt/python@3.8/bin/python3.8)
Mac OS X Catalina 10.15.6 (19G2021)

**Comment by davisagli** [comment]
The EnvironmentProjectKeychain can only read configuration from environment variables, not set it. (This is an operating system limitation: it's not possible for a process to set an environment variable that will last once the process has ended.) For this reason, it's not a keychain you can use if you're running one cci command to create a scratch org and other commands to use that scratch org. The example in the cookbook works because there is a single cci command.

If you need to use a scratch org across multiple calls to cci, the default keychain (which stores configuration in files) is more appropriate.

**Comment by atrancandoris** [comment]
I see. This makes sense as to why it does not work as I expected. But the cookbook is running two separate commands:

       1. cci task run robot --org dev -o vars BROWSER:headlesschrome
       2. cci org scratch_delete dev

So I would argue the Cookbook example is not correct. Should it be updated to properly reflect this behavior?

**Comment by davisagli** [comment]
@atrancandoris oh ok, yes, I think you are right. I was looking at the wrong example in the cookbook. We'll take another look at this.

CumulusCI takes a slightly different approach for its own browser tests: https://github.com/SFDO-Tooling/CumulusCI/blob/master/.github/workflows/feature_test.yml#L141 -- it is using the default keychain. This works because CumulusCI does not have dependencies, so the github service credentials do not need to be loaded from an environment variable. I'll need to think what is the best approach for a project that needs credentials from the environment AND the ability to use scratch org configuration across multiple commands.

**Comment by atrancandoris** [comment]
Thanks for your help. I will use the tests you posted as an example.
