### ISSUE TITLE
Issue creating 2GP packages without namespace

### ISSUE THREAD

**Issue by anspaujd** [SFDO-Tooling/CumulusCI#2089]
**Describe the bug**
When attempting to create a new 2GP package version via the `build_feature_test_package` flow it errors if the project and subsequent packages do not contain a namespace.

**Reproduction steps**
1. Initialize CCI project without namespace
2. Create 2GP package shell
3. Ensure there is some test metadata in force-app repo 
4. Run `build_feature_test_package` flow

**Context**
- Your CumulusCI version (`3.20.1`).
- Your Python version (`Python 2.7.16`)
- MacOS version 10.15.7
- CCI installed via Brew

**Gist**
https://gist.github.com/5587fecec7c132aa45bb35f0a2a8ff90

**Comment by davisagli** [comment]
@anspaujd Are you trying to create a managed 2gp or an unlocked 2gp? The build_feature_test_package flow is specifically defaulting to building a 2gp managed beta package version, because we intend to use it to test Salesforce.org's managed packages. And managed packages must have a namespace.

If you're trying to create an unlocked package, you have a couple options:
1. You can set the package_type option when running the flow: `cci flow run build_feature_test_package --org dev -o create_package_version__package_type Unlocked`
2. You can set `package_type: Unlocked` in the project: package section of cumulusci.yml (same section as the package name)

**Comment by davisagli** [comment]
@anspaujd Are you trying to create a managed 2gp or an unlocked 2gp? The build_feature_test_package flow is specifically defaulting to building a 2gp managed beta package version, because we intend to use it to test Salesforce.org's managed packages. And managed packages must have a namespace.

If you're trying to create an unlocked package, you have a couple options:
1. You can set the package_type option when running the flow: `cci flow run build_feature_test_package --org dev -o create_package_version__package_type Unlocked`
2. You can set `package_type: Unlocked` in the project: package section of cumulusci.yml (same section as the package name)

**Comment by anspaujd** [comment]
@davisagli - Attempting to create unlocked packages. That updated command worked to create a package however it is not pulling the existing package shell and versioning. Currently my sfdx-project.json reads as follows:

`{`
`    "packageDirectories": [`
`        {`
`            "path": "force-app",`
`            "default": true,`
`            "package": "MetaCI_Test",`
`           "versionName": "ver 0.1",`
`            "versionNumber": "0.1.0.NEXT"`
`        }`
`    ],`
`    "namespace": "",`
`    "sourceApiVersion": "49.0",`
`    "packageAliases": {`
`        "MetaCI_Test": "0Ho6g000000XZsjCAG",`
`        "MetaCI_Test@0.1.0-2": "04t6g0000083ixWAAQ"`
`    }
`}`

But when the updated command runs, it outputs:

`Created package version:`
`2020-10-15 09:18:58:   Package2 Id: 0Ho6g000000XZstCAG`
`2020-10-15 09:18:58:   Package2Version Id: 05i6g000000XaS7AAK`
`2020-10-15 09:18:58:   SubscriberPackageVersion Id: 04t6g0000083iy0AAA`
`2020-10-15 09:18:58:   Version Number: 0.0.0.1`
`2020-10-15 09:18:58:   Dependencies: None`

Am I missing something or is this working as expected? It seems odd that the build package command would ignore the existing package shell and create new package at large?

**Comment by davisagli** [comment]
This is working as expected. Our general philosophy with CumulusCI's 2gp support was to try to create a way of releasing and installing 2gp package versions that does not use sfdx-project.json. We think that package and package version metadata belongs outside of the repository for a few reasons:
1. For a repository that is open source or shared, it's conceivable that different parties might release different packages from the same source.
2. It makes it easier to set up an automated release pipeline, because package info doesn't need to be committed back to the repo.
3. It opens the possibility of putting package info in a registry that can be accessed by parties who don't have access to the repository (though this is more hypothetical at this point: so far we've been planning to put this info in git tags, so it would still require read access, similar to how CumulusCI resolves 1gp package versions).

Since we aren't using sfdx-project.json to get the package id, the create_package_version task queries the Dev Hub to see if there is an existing package with the specified package name and type. If found, it'll make a new package version of that package; otherwise it creates a new package. In your case, perhaps there is a mismatch between the existing package name and the package name configured in cumulusci.yml. There should be some log lines further up in the output that show the task checking for an existing package.
