### ISSUE TITLE
Incorrect tests?

### ISSUE THREAD

**Issue by prescod** [SFDO-Tooling/CumulusCI#2303]
We have a mock for push.create_push_request

https://github.com/SFDO-Tooling/CumulusCI/blob/48db7daf2743ae0b518a6af2027c7e899ded4ecb/cumulusci/tasks/push/tests/test_push_tasks.py#L499

The type of the mock is Tuple[dict, int]

The return value for the real function seems to be Tuple[str,int]

https://github.com/SFDO-Tooling/CumulusCI/blob/44b0d6a3e44427652f018e23684e37d232e7eaf0/cumulusci/tasks/push/push_api.py#L584

Perhaps this was hidden by the memoization code?

**Comment by davisagli** [comment]
I don't think it's hidden by the memoization code; I think it's just that the task doesn't do anything with this value except store it in the return values, and the tests didn't make an assertion about it. Fixed in https://github.com/SFDO-Tooling/CumulusCI/pull/2315/commits/4184393965b8f3d27b8a4d4fe0158cc510c1883a
