### ISSUE TITLE
There is no way to connect a persistent org via JWT flow

### ISSUE THREAD

**Issue by edmondo1984** [SFDO-Tooling/CumulusCI#2354]
When you release automatically packages to production, typically in the scope of automated deployment, you have your production org authorized via JWT, i.e. using the cci org connect is not an option because it uses Oauth Web Flow

I think this should be both supported and documented

**Comment by davisagli** [comment]
@edmondo1984 This is possible, but it is not very obvious (it involves setting a number of environment variables, rather than running a cci command) or documented.

I can think of a few different directions we could go to improve our support for this, such as:
a. improve our documentation of the existing support using environment variables
b. improve the `cci org import` command so that it supports persistent orgs which were already connected to sfdx using the force:auth:jwt:grant command
c. add a new cci command (or different options for the `cci org connect` command to support this use case without needing to connect the org to sfdx first

Is one of those ideas what you were thinking, or do you have another suggestion about what would work well?

**Comment by edmondo1984** [comment]
@davisagli I was able to obtain a draft version of the new doc. It is possible, it is just undocumented https://cumulusci.readthedocs.io/en/feature-doc-reorg__continuous_integration/github_actions.html#connect-a-persistent-org

**Comment by Confirm4Crit** [comment]
Hey @edmondo1984 !
That doc you sent is currently not working. 

Does that workaround still work, or was it pulled down for a reason?

**Comment by davisagli** [comment]
@Confirm4Crit It is now part of the published docs: https://cumulusci.readthedocs.io/en/stable/github_actions.html#connect-a-persistent-org

**Comment by RupertBarrow** [comment]
This could be closed, I think
