### ISSUE TITLE
named services is a breaking change and should have been a major version

### ISSUE THREAD

**Issue by avisser** [SFDO-Tooling/CumulusCI#2565]
**Describe the bug**
Our automation scripts do the following
* pip install cumulusci
* cci service connect github --username $GITHUB_USERNAME --token $GITHUB_TOKEN --email xx@yy.com

That worked yesterday, but now fails with 
> Error: Missing argument 'SERVICE_NAME'.

I appreciate the functionality provided by this change, but it is a breaking change. The existing, default behavior should have been preserved. Or at least some warning should have appeared in this version, as if this feature was being deprecated. 

**Context**
Please include the following information at minimum.

* cci version 3.33.0
* python 3.9.4
* macOS 10.14.6

**Comment by davisagli** [comment]
@avisser Apologies for the breaking change in a minor version -- I was forgetting that this command is also used in CI scripts in this fashion.

You can fix the error by adjusting the command to specify a name for the service: e.g. `cci service connect github github.com --username $GITHUB_USERNAME --token $GITHUB_TOKEN --email xx@yy.com`

You can use another name instead of `github.com`. The first github service that you connect will be used by default.

**Comment by davisagli** [comment]
@avisser fwiw, we are going to change this so that the service name is optional, and try to get that released later today.

Generally we try hard to avoid breaking changes like this, and I think we are usually pretty successful, but obviously this one slipped through. Pinning to a specific version is the way to avoid surprises -- perhaps you can pin 3.33 but then revisit periodically to update (with a CI build to verify the new version before merging the update to the pin).

**Comment by davisagli** [comment]
@avisser We just released cumulusci 3.33.1 which restores the ability to run `cci service connect` without specifying a service name (it will use the name "default")
