### ISSUE TITLE
AddValueSetEntries does not update TaskStatus "closed" field

### ISSUE THREAD

**Issue by edmondo1984** [SFDO-Tooling/CumulusCI#2690]
**Describe the bug**
When you use the task AddValueSetEntries to add TaskStatus values, if you deploy the value set entries and then you change the "closed" value and you try again, the updated closed value is not deployed

**Reproduction steps**
1. Create a custom task AddValueSetEntries for TaskStatus value with closed = false
2. Run the task against an org
3. Update the entries with closed = true
4. Run the task against the same org
5. Check, the closed value has not been updated

**Context**
Please include the following information at minimum.
CumulusCI version: 3.35.0 
Python version: 3.8.0

**Comment by davidmreed** [comment]
This is working as designed. The `AddValueSetEntries` task takes no action if the desired values are already present. That's because this task (and all Metadata ETL tasks) are designed to perform minimal, safe interventions in customer orgs, without unexpected side effects. This task in particular does not perform an "upsert" of picklist values.
