### ISSUE TITLE
"Commit None" Error Occurs Whenever qa_org_2gp is run on a Commit instead of a Branch

### ISSUE THREAD

**Issue by Julian88Tex** [SFDO-Tooling/CumulusCI#2801]
**Describe the bug**
When running `qa_org_2gp` from a checked out a commit, an error mentioning "commit None" occurs.

**Reproduction steps**
1. Check out a commit
2. Run `qa_org_2gp` against an org

**Context**
Please include the following information at minimum.

- 3.41.0
- 3.9.6
- macOS 11.5.1 (20G80)

**Error**
```
2021-08-13 17:06:14: Could not find commit None on GitHub
2021-08-13 17:06:14: This error usually means your local commit has not been pushed or that a feature test package has not yet been built.
2021-08-13 17:06:14: Exception in task install_2gp_commit.github_package_data

Could not find package version id in 'Build Feature Test Package' commit status for commit None.
```

**Additional information**
@davisagli suggested that this may be caused by checking out a commit vs. a branch.

**Comment by davidmreed** [comment]
Tracking as W-9786099.

**Comment by davisagli** [comment]
We're fixing this, but note that if you do a 2gp build in this state, CumulusCI won't know what release branch the commit is associated with, which means that it won't be able to pick the matching release branch from dependencies.

**Comment by Julian88Tex** [comment]
@davisagli Hm, what would happen in that case then? Use the most recent release? Would it make sense to have a prompt or a Warning to inform users what is happening and why and how to add a specific release if they wanted one?

**Comment by davisagli** [comment]
@Julian88Tex if the current branch doesn't start with feature/xxx where xxx is a release number, then cci will install the most recent beta of dependencies (i.e. from the main branch), instead of looking for the most recent 2gp created from the matching feature/xxx branch.

Do you have a suggestion for how to word a warning in a way that reduces rather than adds confusion? Remember that we don't know if the detached-head commit is from a release branch or not, so it's hard to know the user's intent.

**Comment by Julian88Tex** [comment]
@davisagli I don't know if this is possible in git, but if it is possible to know which branch the commit was originally for, then using that as the way to find a release makes sense.

Regarding a warning, of course, it should be formated similarly to other CCI warnings but here's a stab at it as best I understand it:

"Warning: You have checked out a commit/branch that is not in "feature/<release_number>" naming format. CumlusCI is unable to determine any release-specific 2GP version dependencies and will instead use the most recent beta version's dependencies."

**Comment by davisagli** [comment]
@Julian88Tex no, that's the problem, if you check out a specific commit, we don't know what branch it's from (there could be multiple branches that include the commit -- or no branches!)

A warning along these lines may be possible -- we'll need to take a look and make sure it's something that we can do only if the project is actually trying to resolve dependencies using the 2gp resolver, so that we don't add unnecessary noise

**Comment by Julian88Tex** [comment]
@davisagli Makes sense!
