### ISSUE TITLE
Cannot initialize a cci project in a git worktree

### ISSUE THREAD

**Issue by cdelmoral** [SFDO-Tooling/CumulusCI#3268]
### Describe the bug

When using a git worktree the `cci project init` command fails with the error:

```
$ cci project init 
Error: You are not in the root of a Git repository
Run this command for more information about debugging errors: cci error --help
```

### Reproduction steps

Run the following commands in a terminal:

1. `git clone --bare https://github.com/trailheadapps/dreamhouse-lwc.git dreamhouse-lwc`
2. `cd dreamhouse-lwc`
3. `git worktree add main`
4. `cd main`
5. `cci project init`

**Expected Behavior**

The CumulusCI project is initialized.

**Current Behavior**

The following error is displayed:

```
Error: You are not in the root of a Git repository
Run this command for more information about debugging errors: cci error --help
```

### Your CumulusCI and Python versions

```
CumulusCI version: 3.60.0 (~/.local/bin/cci)
Python version: 3.10.2 (~/.local/pipx/venvs/cumulusci/bin/python)

You have the latest version of CumulusCI ⛅

See the latest CumulusCI Release Notes: https://github.com/SFDO-Tooling/CumulusCI/releases/tag/v3.60.0
```

### Operating System

macOS Monterey Version 12.4

**Comment by davidmreed** [comment]
I admittedly had not heard of Git worktrees until I read the manpage this morning. 

At first glance, adding comprehensive support for worktrees to CumulusCI is likely to be fairly complex because of the extent to which CumulusCI automation relies on knowing which (exactly one) commit it is operating in, and on the associated filesystem structures. 

That said, I would anticipate CumulusCI would work in a worktrees repo provided you don't check it out as a bare repo - I would expect it to ignore the linked worktrees and use the "main worktree" as described in the documentation.

**Comment by jstvz** [comment]
Because CumulusCI interacts directly with the contents of `.git/` (and does not respect `GIT_DIR`) it does not support bare checkouts ([docs](https://cumulusci.readthedocs.io/en/stable/concepts.html#project-directory)).
